server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true        # ← add this

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: AIzaSyAhfjl_1BNqUiluhlu0l324bR1JySp7WOg